projectTitle = "EscapeScreen"
modId = "escape_screen"
modVersion = "2.0.0"
group = "com.theendercore"
githubRepo = "theendercore/EscapeScreen"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = ">=1.21.9-rc.1"
minecraftVersion = "1.21.9-rc1"
fabricLoaderVersion = "0.17.2"
fabricApiVersion = "0.133.13+1.21.9"
fabricLangKotlinVersion = "1.13.2+kotlin.2.1.20"
license = "MIT"
modules = [ ]
modDescription = "A mod to remap the esc key!"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = true

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.9-rc1"