projectTitle = "EscapeScreen"
modId = "escape_screen"
modVersion = "1.2.0"
group = "com.theendercore"
githubRepo = "theendercore/EscapeScreen"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.16.13"
fabricApiVersion = "0.115.4+1.21.1"
fabricLangKotlinVersion = "1.13.2+kotlin.2.1.20"
license = "MIT"
modules = [ ]
modDescription = "A mod to remap the esc key!"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = true

[mappings]
# You have 7 mapping types
# MOJANG: The official Mojang mappings
# YARN: Yarn mappings
# PARCHMENT: Parchment mappings
# QUILT: Quilt mappings
# MOJPARCH: Parchment layered on top of the official Mojang mappings
# MOJYARN: Yarn layered on top of the official Mojang mappings
# CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "YARN"
    version = "1.21.1+build.3"