[versions]
kotlin = "2.2.20"
fabric-loom = "1.11-SNAPSHOT"
iridium = "3.5.0"

# Dev
controlling = "18.0.4"
# Testing
modmenu = "11.0.3"
#creative-works = "0.5.0"
#imguimc = "1.21.1-1.0.8"
#fzzy-config = "0.7.2+1.21"

[libraries]
#modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
controlling = { module = "com.blamejared.controlling:Controlling-fabric-1.21", version.ref = "controlling"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }
